import path from 'node:path';
import type {
  ParsedSession,
  ConversationTurn,
  AssistantMessage,
  ToolCall,
  FormatOptions,
} from '../core/types.js';
import {
  formatDuration,
  formatTimestamp,
  truncateLines,
  details,
  fencedCodeBlock,
  escapeDetailsContent,
  formatToolInput,
} from './templates.js';

const DEFAULT_OPTIONS: FormatOptions = {
  noFilter: false,
  projectPath: '',
};

/** Max lines for tool results in no-filter mode */
const MAX_TOOL_RESULT_LINES = 50;

/**
 * Format a parsed session into Markdown.
 */
export function formatSession(
  session: ParsedSession,
  options: Partial<FormatOptions> = {}
): string {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const parts: string[] = [];

  parts.push(renderHeader(session, opts));

  for (const turn of session.turns) {
    parts.push(renderTurn(turn, opts));
  }

  const footer = '\n\n---\n\n*Generated by [ccdigest](https://github.com/henteko/ccdigest)*';
  return parts.join('\n\n---\n\n') + footer + '\n';
}

function renderHeader(session: ParsedSession, opts: FormatOptions): string {
  const { metadata } = session;
  const lines: string[] = [];
  const isMerged = metadata.sessionId.includes(',');

  if (isMerged) {
    lines.push('# Merged Session Report');
    lines.push('');
    const ids = metadata.sessionId.split(',');
    lines.push(`- **Sessions** (${ids.length}):`);
    for (const id of ids) {
      lines.push(`  - \`${id}\``);
    }
  } else {
    lines.push('# Session Report');
    lines.push('');
    lines.push(`- **Session ID**: \`${metadata.sessionId}\``);
  }

  // Filter mode: show basename only; no-filter: show full path
  const projectDisplay = opts.noFilter
    ? metadata.project
    : path.basename(metadata.project);
  lines.push(`- **Project**: \`${projectDisplay}\``);

  if (metadata.branch) {
    lines.push(`- **Branch**: \`${metadata.branch}\``);
  }

  if (metadata.model) {
    lines.push(`- **Model**: \`${metadata.model}\``);
  }

  if (metadata.startTime && metadata.endTime) {
    const start = formatTimestamp(metadata.startTime);
    const end = formatTimestamp(metadata.endTime);
    const durationMs =
      new Date(metadata.endTime).getTime() - new Date(metadata.startTime).getTime();
    const duration = formatDuration(durationMs);

    if (start === end) {
      lines.push(`- **Date**: ${start}`);
    } else {
      lines.push(`- **Date**: ${start} - ${end} (${duration})`);
    }
  }

  if (session.turns.length > 0) {
    lines.push(`- **Turns**: ${session.turns.length}`);
  }

  lines.push(`- **Generated by**: [ccdigest](https://github.com/henteko/ccdigest)`);

  return lines.join('\n');
}

function renderTurn(turn: ConversationTurn, opts: FormatOptions): string {
  const parts: string[] = [];

  // Turn header
  let turnHeader = `## Turn ${turn.turnNumber}`;
  if (turn.durationMs) {
    turnHeader += ` (${formatDuration(turn.durationMs)})`;
  }
  parts.push(turnHeader);

  // User message
  parts.push('### User');
  parts.push(
    turn.userMessage
      .split('\n')
      .map((line) => `> ${line}`)
      .join('\n')
  );

  // Assistant messages
  for (const msg of turn.assistantMessages) {
    parts.push(renderAssistantMessage(msg, opts));
  }

  return parts.join('\n\n');
}

function renderAssistantMessage(
  msg: AssistantMessage,
  opts: FormatOptions
): string {
  const parts: string[] = [];

  parts.push('### Assistant');

  // Thinking blocks: hidden in filter mode, collapsed in no-filter mode
  if (opts.noFilter && msg.thinkingBlocks.length > 0) {
    const thinking = escapeDetailsContent(msg.thinkingBlocks.join('\n\n'));
    parts.push(details('Thinking', thinking, false));
  }

  // Text blocks
  for (const text of msg.textBlocks) {
    parts.push(text);
  }

  // Tool calls: always shown
  for (const tc of msg.toolCalls) {
    parts.push(renderToolCall(tc, opts));
  }

  return parts.join('\n\n');
}

function renderToolCall(tc: ToolCall, opts: FormatOptions): string {
  // In filter mode, relativize paths; in no-filter mode, show full paths
  const projectPath = opts.noFilter ? undefined : opts.projectPath;
  const inputDisplay = formatToolInput(tc.name, tc.input, projectPath);
  const header = inputDisplay
    ? `**Tool: ${tc.name}** (${inputDisplay})`
    : `**Tool: ${tc.name}**`;

  // In filter mode, hide tool results entirely
  if (!opts.noFilter) {
    return header;
  }

  // In no-filter mode, show results truncated to MAX_TOOL_RESULT_LINES
  if (!tc.result) {
    return header;
  }

  const { text, truncated, totalLines } = truncateLines(tc.result, MAX_TOOL_RESULT_LINES);
  const summaryExtra = truncated
    ? ` (${totalLines} lines, showing first ${MAX_TOOL_RESULT_LINES})`
    : ` (${totalLines} lines)`;
  const codeContent = truncated ? text + '\n...' : text;

  return `${header}\n\n${details(`Result${summaryExtra}`, fencedCodeBlock(codeContent), false)}`;
}
